version: "3.8"

name: ${ADMINER_NAME}

services:
  adminer:
    image: adminer
    environment:
      - ADMINER_DESIGN=${ADMINER_DESIGN}
    container_name: ${ADMINER_NAME}
    restart: unless-stopped
    networks:
      public:
      private:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`${ADMINER_NAME}.${BASE_DOMAIN}`)"

#volumes:

networks:
  public:
    name: public
    external: true
  private:
    name: private
    external: true

#secrets:

#configs:
