version: "3.8"

name: ${GITEA_NAME}

services:
  gitea:
    image: gitea/gitea
    env_file:
      - path: ./gitea/.gitea.default
        required: false
      - path: ./gitea/.gitea.custom
        required: false
    container_name: ${GITEA_NAME}
    restart: unless-stopped
    volumes:
      - ${GITEA_NAME}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      private:
      public:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`${GITEA_NAME}.${BASE_DOMAIN}`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"

volumes:
  gitea:
    name: ${GITEA_NAME}

networks:
  public:
    name: public
    external: true
  private:
    name: private
    external: true

#secrets:

#configs:
