version: "3.8"

name: ${HOMEPAGE_NAME}

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: ${HOMEPAGE_NAME}
    restart: unless-stopped
    environment:
      - PUID=${HOMEPAGE_PUID}
      - GUID=${HOMEPAGE_GUID}
    volumes:
      - ./homepage/config:/app/config
    networks:
      public:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.${BASE_DOMAIN}`)"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"

#volumes:

networks:
  public:
    name: public
    external: true

#secrets:

#configs:
