version: "3.8"

name: ${HOMEPAGE_NAME}

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: ${HOMEPAGE_NAME}
    restart: unless-stopped
    env_file:
      - path: ./homepage/.homepage.default
        required: false
      - path: ./homepage/.homepage.custom
        required: false
    volumes:
      - ${HOMEPAGE_CONFIG}:/app/config
    networks:
      public:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`${HOMEPAGE_NAME}.${BASE_DOMAIN}`)"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"

#volumes:

networks:
  public:
    name: public
    external: true

#secrets:

#configs:
