# -------
# Keycloak: https://www.keycloak.org/
# -------

version: "3.8"

name: ${KEYCLOAK_NAME}

services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_TAG}
    env_file:
      - path: ./keycloak/.keycloak.default
        required: false
      - path: ./keycloak/.keycloak.custom
        required: false
    command:
      - start-dev
    container_name: ${KEYCLOAK_NAME}
    restart: always
    networks:
      public:
      private:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_NAME}.${BASE_DOMAIN}`)"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master"]
      start_period: 10s
      interval: 30s
      retries: 5
      timeout: 5s

#volumes:

networks:
  public:
    name: public
    external: true
  private:
    name: private
    external: true

#secrets:

#configs:
