# -------
# Keycloak: https://www.keycloak.org/
# -------

version: "3.8"

name: ${KEYCLOAK_NAME}

services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_TAG}
    environment:
      - KC_DB=${KEYCLOAK_DB}
      - KC_DB_URL=${KEYCLOAK_DB_URL}
      - KC_DB_USERNAME=${KEYCLOAK_DB_USERNAME}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KC_HOSTNAME=${KEYCLOAK_HOSTNAME}
      - KC_HOSTNAME_PORT=${KEYCLOAK_HOSTNAME_PORT}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    command:
      - start-dev
    container_name: ${KEYCLOAK_NAME}
    restart: always
    networks:
      public:
      private:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_NAME}.${BASE_DOMAIN}`)"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"

#volumes:

networks:
  public:
    name: public
    external: true
  private:
    name: private
    external: true

#secrets:

#configs:
