version: "3.8"

name: mysql

services:
  mysql:
    image:
    container_name: mysql
    volumes:
      - mysql:/
    networks:
      private:
    #labels:

volumes:
  mysql:
    name: mysql

networks:
  private:
    name: private
    external: true

#secrets:

#configs:
