version: "3.8"

name: portainer

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    networks:
      public:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${BASE_DOMAIN}`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

volumes:
  portainer:
    name: portainer

networks:
  public:
    name: public
    external: true

#secrets:

#configs:
