version: "3.8"

name: ${POSTGRES_NAME}

services:
  postgres:
    image: postgres:${POSTGRES_TAG}
    env_file:
      - path: ./postgres/.postgres.default
        required: false
      - path: ./postgres/.postgres.custom
        required: false
    container_name: ${POSTGRES_NAME}
    restart: always
    hostname: ${POSTGRES_HOSTNAME}
    volumes:
      - ${POSTGRES_NAME}:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      private:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  postgres:
    name: ${POSTGRES_NAME}

networks:
  private:
    name: private
    external: true

#secrets:

#configs:
