version: "3.8"

name: ${REDISCOMMANDER_NAME}

services:
  rediscommander:
    image: ghcr.io/joeferner/redis-commander:${REDISCOMMANDER_TAG}
    container_name: ${REDISCOMMANDER_NAME}
    env_file:
      - path: ./rediscommander/.rediscommander.default
        required: false
      - path: ./rediscommander/.rediscommander.custom
        required: false
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      public:
      private:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${REDISCOMMANDER_NAME}.rule=Host(`${REDISCOMMANDER_NAME}.${BASE_DOMAIN}`)"
      - "traefik.http.services.${REDISCOMMANDER_NAME}.loadbalancer.server.port=8081"

#volumes:

networks:
  public:
    name: public
    external: true
  private:
    name: private
    external: true

#secrets:

#configs:
