version: "3.8"

name: ${MYSQL_NAME}

services:
  mysql:
    image: mysql:${MYSQL_TAG}
    container_name: ${MYSQL_NAME}
    env_file:
      - path: ./mysql/.mysql.default
        required: false
      - path: ./mysql/.mysql.custom
        required: false
    hostname: ${MYSQL_HOSTNAME}
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${MYSQL_NAME}:/var/lib/mysql
    networks:
      private:
    # TODO: add healthcheck

volumes:
  mysql:
    name: ${MYSQL_NAME}

networks:
  private:
    name: private
    external: true

#secrets:

#configs:
