# -------
# DockerHub: https://hub.docker.com/_/rabbitmq
# -------

version: "3.8"

name: ${RABBITMQ_NAME}

services:
  rabbitmq:
    image: rabbitmq:${RABBITMQ_TAG}
    container_name: ${RABBITMQ_NAME}
    hostname: ${RABBITMQ_HOSTNAME}
    env_file:
      - path: ./rabbitmq/.rabbitmq.default
        required: false
      - path: ./rabbitmq/.rabbitmq.custom
        required: false
    restart: always
    volumes:
      - ${RABBITMQ_NAME}:/var/lib/rabbitmq
    networks:
      private:

volumes:
  rabbitmq:
    name: ${RABBITMQ_NAME}

networks:
  private:
    name: private
    external: true

#secrets:

#configs:
